### Homework 1 
    8-puzzle & 15-puzzle  
    Gianluca Rea

### Libraries and variables definition

In [1]:
### Libraries import
import numpy as np
import random
import time
from copy import deepcopy

In [2]:
### On the board an empty cell is represented using the value 0
step = ["up","down","left","right"];

### Functions and Heuristics

In [3]:
### The following two function are realized to prevent the creation of non solvible board 
def getInvCount(arr,n):
    invCount = 0
    emptyValue = 0
    for i in range (0,n*n):
        for j in range (i+1,n*n):
            if arr[j] != emptyValue and arr[i] != emptyValue and arr[i] > arr[j]:
                invCount += 1
    return invCount

def hasSolution(puzzle,n):
    invCount = getInvCount([j for sub in puzzle for j in sub], n)
    if(n%2==1): return (invCount % 2 == 0)    
    blankPos = 4 - np.where(puzzle == 0)[0]
    return (invCount % 2 != blankPos % 2)


In [4]:
### createWorld(N) create a board of dimension n using the previous 
### function to create a solvible one.

def createWorld(n):
    board =[i for i in range(1,n*n)]
    board.append(0)
    board = np.array(board).reshape(n,n)
    while(True):
        Q = np.arange(n*n)
        np.random.shuffle(Q)
        Q = Q.reshape(n,n)
        if(hasSolution(Q, n)): break
    return Q, board

Q, board = (createWorld(4))

In [5]:
### The function neighbors(state,n) given the current state and dimension n of the building 
### array of the matrix n gives back the position of the empty cell and the all the possible 
### steps even the ones not feasible 

def neighbors(state, n):
    i, j = np.where(state == 0)
    i, j = i[0], j[0]
    up =  (i-1,j) if (i-1>-1) else (None)
    down =  (i+1,j) if (i+1<n) else (None)
    right =  (i,j+1) if (j+1<n) else (None)
    left =  (i,j-1) if (j-1>-1) else (None)
    
    return (i,j),[up, down, left, right]

for indx, val in enumerate(neighbors(Q, 4)[1]):
    
    if val != None:
        i, j = val
        print(step[indx],":", i, j)
    else :
        print(step[indx],":", None)
 

up : 2 3
down : None
left : 3 2
right : None


In [6]:
### Manahattan distance heuristic

def manahattanDistance(state, n):
    mDistances = 0
    for index in range(1,n*n):
        iGoal, jGoal = np.where(board == index)
        iValue, jValue = np.where(state == index)
        manahattanDistanceVar = abs(iValue - iGoal) + abs(jValue - jGoal)
        mDistances +=  manahattanDistanceVar 
    return mDistances[0]


In [7]:
### Misplaced tiles heuristic
### We use this heuristics to count how many pieces are misplaced 

def misplacedTiles(state, n):
    misplacedTilesVar = 0
    for indx, val in enumerate(state.reshape(n*n)):
        if indx +1 != val and val != 0 :
            misplacedTilesVar = misplacedTilesVar +1
    
    return misplacedTilesVar

In [8]:
### The function makeMoves takes as input the state, the position of the empy cell and all the feasible moves
### and as output a list with all the new states

def makeMoves(boardState, positionZero , feasibleMoves ):
    newStatesList = []
    iZero, jZero = positionZero
    for move in feasibleMoves:
        if move != None:
            i, j = move
            newState = np.copy(boardState)
            newState[iZero,jZero], newState[i,j] = newState[i,j], newState[iZero,jZero]
            newStatesList.append(newState)
            
    return newStatesList

### Agents

In [9]:
### All the agents are optimised , for each new state created from the previous one
### we check if the new state are equal to the current one. This way we don't explore every tree 
### saving memory and execution time

### Agent 1 implements the Manahattan Distance heuristic
### Agent 2 implements the Misplaced Tiles heuristic

In [10]:
def agent1(Q, n, board):
    startTime = time.time()

    currentState = Q
    previousState = Q
    i = 0
    while (not np.allclose(board, currentState)):
        i+=1   
        positionZero, feasibleMoves = (neighbors(currentState, n ))                             
        newStateBoards = makeMoves(currentState, positionZero , feasibleMoves)    
        heuristicValues = []
        boardStates = []
        for newStateBoard in newStateBoards:
            if not np.allclose(newStateBoard, previousState):
                boardStates.append(newStateBoard)
                heuristicValues.append(manahattanDistance(newStateBoard, n))
        indexMin = random.choice([i for i, x in enumerate(heuristicValues) if x == min(heuristicValues)])
        previousState = currentState
        currentState = boardStates[indexMin]
    print("--- %s seconds ---" % (time.time() - startTime))

    return(currentState,i)

In [11]:
def agent2(Q, n, board):
    startTime = time.time()

    currentState = Q
    previousState = Q
    i = 0
    while (not np.allclose(board, currentState)):
        i+=1   
        positionZero, feasibleMoves = (neighbors(currentState, n ))                            
        newStateBoards = makeMoves(currentState, positionZero, feasibleMoves)    
        heuristicValues = []
        boardStates = []
        for newStateBoard in newStateBoards:
            if not np.allclose(newStateBoard, previousState):
                boardStates.append(newStateBoard)
                heuristicValues.append(misplacedTiles(newStateBoard, n))
        indexMin = random.choice([i for i, x in enumerate(heuristicValues) if x == min(heuristicValues)])
        previousState = currentState
        currentState = boardStates[indexMin]
    print("--- %s seconds ---" % (time.time() - startTime))

   
    return(currentState,i)

### Bredth First Search and Depth First Search Implementation

In [12]:
### The class node is needed for modeling the tree,
### in this way we can easily implement a DFS and BFS

class Node(object):
    def __init__(self, name: int, data: np.array, parent, notVisited = None):
        self.name = name
        self.data = data
        self.parent = parent
        self.notVisited = notVisited

    def getParent(self) :
        return self.parent

In [13]:
### BFS
def bredthFirstSearch(puzzle: np.array, n, board) : 
    startTime = time.time()

    sol = False
    firstNode = Node(1,puzzle, board)
    explorationNodes = [firstNode]
    j = 0
    i = 1
    while(not sol):
        j = j+1
        listX = []
        print(j, len(explorationNodes))
        for node in explorationNodes:
            if(np.allclose(node.data, board)):
                sol = True
                print("--- %s seconds ---" % (time.time() - startTime))
                return node.data
               
            else:
               
                index, feasibleMoves = neighbors(node.data, n)
                toExplore =  makeMoves(node.data, index, feasibleMoves)
               
                for nodeX in toExplore:
                    i = i+1
                    if (not np.allclose(nodeX, node.getParent().data )):
                        child = Node(i+1, nodeX, node)
                        listX.append(child)
               
            explorationNodes = listX

In [14]:
def depthFirstSearch(puzzle: np.array, n, board) : 
    startTime = time.time()
    stack = [] 
    visited = set()
    gol = Node(-1, board,None, [])
    firstNode = Node(0, puzzle,gol, [])
    stack.append(deepcopy(firstNode)) 
    while (len(stack) !=0): 
        newNode = stack.pop() 
        if newNode not in visited:
            if (np.allclose(newNode.data, board)):
                print("--- %s seconds ---" % (time.time() - startTime))
                return (newNode.name, newNode.data)
            visited.add(newNode) 
        else:
            index, feasibleMoves = neighbors(newNode.data, n)
            newNode.not_visited =  makeMoves(newNode.data, index, feasibleMoves)
            newNode.not_visited.reverse()
            for neighbor in newNode.not_visited:
                if not np.allclose(neighbor, newNode.parent.data):
                    neighborNode = Node(i, neighbor, newNode, [])
                    if neighborNode not in visited: 
                        stack.append(neighborNode) 


# Tests

In [15]:
#Easy example
n = 3
Q, board = (createWorld(n))
print()
print(agent1(Q, n, board))
print()
print(agent2(Q, n, board))


--- 0.03123307228088379 seconds ---
(array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]]), 147)

--- 0.7174451351165771 seconds ---
(array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]]), 6875)


In [16]:
### We show number of iteration, cardinality of explored nodes, execution time
### and solution
print(bredthFirstSearch(Q, n, board))

1 1
2 3
3 5
4 10
5 14
6 28
7 44
8 88
9 128
10 256
11 392
12 784
13 1160
14 2320
15 3512
16 7024
17 10472
18 20944
19 31544
20 63088
21 94376
22 188752
23 283640
24 567280
--- 79.72678112983704 seconds ---
[[1 2 3]
 [4 5 6]
 [7 8 0]]


In [17]:
# Only in easy solvible board is possible to find a solution using DFS
print(depthFirstSearch(Q, n, board))


None


In [18]:
# This is an home made example to show 
board = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,0]])
Q = np.array([[2,0,1,4], [3,8,5,7], [9,6,11,12],[10,13,14,15]])
n = 4

print()
print(agent1(Q, n, board))
print()
#print(agent2(Q, n, board))


--- 2.503391981124878 seconds ---
(array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]]), 6797)



In [ ]:
print(bredthFirstSearch(Q, n, board))
print()
## print(depthFirstSearch(Q,n,board))

1 1
2 3
3 6
4 14
5 32
6 66
7 136
8 290
9 624
10 1338
11 2848
12 6042
13 12856
14 27426
15 58488
16 124594
17 265312
18 565098
19 1204016
20 2565418
21 5465448
22 11642898
23 24803144
